export const DECREASE_BREAK = 'DECREASE_BREAK';
export const INCREASE_BREAK = 'INCREASE_BREAK';
export const DECREASE_SESSION = 'DECREASE_SESSION';
export const INCREASE_SESSION = 'INCREASE_SESSION';
export const DECREASE_TIMER = 'DECREASE_TIMER';
